name: parse

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:     
      - name: Cache preparation
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}-preparation
          
      - uses: actions/checkout@v2
        
      - name: setup
        run: |
          pip install requests
          pip install lxml
          pip install beautifulsoup4
      
      - name: rm
        run: |
          rm -rf latest/*

      - name: python
        run: |
          python create_urls.py

      - name: errors
        run: |
          cat latest/urls_errors.txt
          

  errors_check_1:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Cache errors_check_1
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}-errors_check_1

      - name: Cache preparation
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}-preparation
        
      - name: setup
        run: |
          pip install requests
          pip install lxml
          pip install beautifulsoup4

      - name: python
        run: |
          python urls_errors_check.py

      - name: errors
        run: |
          cat latest/urls_errors.txt
                    

  errors_check_2:
    runs-on: ubuntu-latest
    needs: errors_check_1
    steps:
      - name: Cache errors_check_2
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}-errors_check_2

      - name: Cache errors_check_1
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}-errors_check_1

      - name: setup
        run: |
          pip install requests
          pip install lxml
          pip install beautifulsoup4

      - name: python
        run: |
          python urls_errors_check.py

      - name: errors
        run: |
          cat latest/urls_errors.txt
            
      # - name: tree
      #   run: |
      #     sudo apt install -y tree
      #     tree
      
  download_0:
    runs-on: ubuntu-latest
    needs: errors_check_2
    steps:
      - name: Cache 
        uses: actions/cache@v2
        with:
          path: latest/pages/0/*
          key: ${{ github.sha }}-download_0

      - name: Cache 
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}-errors_check_2
                    
      - name: setup
        run: |
          pip install BeautifulSoup4
          pip install requests
          pip install eventlet

      - name: download pages
        run: |
          python3 download.py 200 0
            
  download_200:
    runs-on: ubuntu-latest
    needs: errors_check_2
    steps:
      - name: Cache 
        uses: actions/cache@v2
        with:
          path: latest/pages/200/*
          key: ${{ github.sha }}-download_200

      - name: Cache 
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}-errors_check_2
                    
      - name: setup
        run: |
          pip install BeautifulSoup4
          pip install requests
          pip install eventlet

      - name: download pages
        run: |
          python3 download.py 200 200
            
  download_400:
    runs-on: ubuntu-latest
    needs: errors_check_2
    steps:
      - name: Cache 
        uses: actions/cache@v2
        with:
          path: latest/pages/400/*
          key: ${{ github.sha }}-download_400

      - name: Cache 
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}-errors_check_2
                    
      - name: setup
        run: |
          pip install BeautifulSoup4
          pip install requests
          pip install eventlet

      - name: download pages
        run: |
          python3 download.py 200 400
            
  assembling:
    runs-on: ubuntu-latest
    needs: [download_0, download_200, download_400, ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache assembled
        uses: actions/cache@v2
        with:
          path: latest/*
          key: ${{ github.sha }}-assembled
      
      - name: Cache download_0
        uses: actions/cache@v2
        with:
          path: latest/pages/0/*
          key: ${{ github.sha }}-download_0
      
      - name: Cache download_200
        uses: actions/cache@v2
        with:
          path: latest/pages/200/*
          key: ${{ github.sha }}-download_200
      
      - name: Cache download_400
        uses: actions/cache@v2
        with:
          path: latest/pages/400/*
          key: ${{ github.sha }}-download_400

  download_errors_check_1:
    runs-on: ubuntu-latest
    needs: assembling
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache download_errors_check_1
        uses: actions/cache@v2
        with:
          path: latest/*
          key: ${{ github.sha }}-download_errors_check_1
          
      - name: Cache assembled
        uses: actions/cache@v2
        with:
          path: latest/*
          key: ${{ github.sha }}-assembled

      - name: setup
        run: |
          pip install BeautifulSoup4
          pip install requests
          pip install eventlet

      - name: download pages
        run: |
          python3 download_errors_check.py 200 
    
      - name: errors
        run: |
          cat latest/pages/download_errors.txt || echo No errors


  download_errors_check_2:
    runs-on: ubuntu-latest
    needs: download_errors_check_1
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache download_errors_check_2
        uses: actions/cache@v2
        with:
          path: latest/*
          key: ${{ github.sha }}-download_errors_check_2

      - name: Cache download_errors_check_1
        uses: actions/cache@v2
        with:
          path: latest/*
          key: ${{ github.sha }}-download_errors_check_1

      - name: setup
        run: |
          pip install BeautifulSoup4
          pip install requests
          pip install eventlet

      - name: download pages
        run: |
          python3 download_errors_check.py 200 
    
      - name: errors
        run: |
          cat latest/pages/download_errors.txt || echo No errors

  parse:
    runs-on: ubuntu-latest
    needs: download_errors_check_2
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache 
        uses: actions/cache@v2
        id: download_errors_check_2
        with:
          path: latest/*
          key: ${{ github.sha }}-download_errors_check_2
          
      - name: setup 
        run: | 
          pip install pandas
          pip install lxml
          pip install BeautifulSoup4
      
      - name: tree
        run: |
          sudo apt install -y tree
          tree
          
      - name: python
        run: |
          python parse.py || echo error
          
      # - name: rm
      #   run: |
      #     rm -rf latest/*
          
      - name: tree
        run: |
          tree
              
      - name: setup git
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_NAME: ${{ secrets.GIT_NAME }}
        run: |
          git config --global user.email $GIT_EMAIL
          git config --global user.name $GIT_NAME
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install -y git-lfs
          git lfs install

      - name: git add 
        run: |
          date=$(date '+%Y-%m-%d_%H:%M:%S')
          git add -A
          git commit -m $date

      - name: git push
        run: |
          git push

